import { CircuitInfo } from '../types';

export const circuitData: Record<string, CircuitInfo> = {
  'Albert Park Circuit': {
    id: 'albert-park',
    name: 'Albert Park Circuit',
    location: 'Melbourne',
    country: 'Australia',
    length: '5.278 km',
    laps: 58,
    lap_record: '1:20.235',
    lap_record_driver: 'Charles Leclerc (2024)',
    first_gp: 1996,
    type: 'Street',
    elevation: 'Flat',
    corners: 14,
    drs_zones: 4,
    description: 'A picturesque semi-street circuit around Melbourne\'s Albert Park Lake. Known for its fast, flowing nature and unpredictable sessions.',
  },
  'Shanghai International Circuit': {
    id: 'shanghai',
    name: 'Shanghai International Circuit',
    location: 'Shanghai',
    country: 'China',
    length: '5.451 km',
    laps: 56,
    lap_record: '1:32.238',
    lap_record_driver: 'Michael Schumacher (2004)',
    first_gp: 2004,
    type: 'Permanent',
    elevation: 'Flat',
    corners: 16,
    drs_zones: 2,
    description: 'Designed by Hermann Tilke, featuring a demanding opening sector and one of F1\'s longest back straights.',
  },
  'Suzuka International Racing Course': {
    id: 'suzuka',
    name: 'Suzuka International Racing Course',
    location: 'Suzuka',
    country: 'Japan',
    length: '5.807 km',
    laps: 53,
    lap_record: '1:30.839',
    lap_record_driver: 'Lewis Hamilton (2019)',
    first_gp: 1987,
    type: 'Permanent',
    elevation: 'Undulating',
    corners: 18,
    drs_zones: 1,
    description: 'A figure-eight masterpiece beloved by drivers. The Esses, Spoon Curve, and 130R make it one of the ultimate driving challenges.',
  },
  'Miami International Autodrome': {
    id: 'miami',
    name: 'Miami International Autodrome',
    location: 'Miami Gardens',
    country: 'United States',
    length: '5.412 km',
    laps: 57,
    lap_record: '1:29.708',
    lap_record_driver: 'Max Verstappen (2023)',
    first_gp: 2022,
    type: 'Street',
    elevation: 'Flat',
    corners: 19,
    drs_zones: 3,
    description: 'A high-speed street circuit around Hard Rock Stadium, featuring a fake marina and tight, technical sections.',
  },
  'Circuit Gilles Villeneuve': {
    id: 'montreal',
    name: 'Circuit Gilles Villeneuve',
    location: 'Montreal',
    country: 'Canada',
    length: '4.361 km',
    laps: 70,
    lap_record: '1:13.078',
    lap_record_driver: 'Valtteri Bottas (2019)',
    first_gp: 1978,
    type: 'Street',
    elevation: 'Flat',
    corners: 14,
    drs_zones: 2,
    description: 'Located on Île Notre-Dame, famous for the Wall of Champions and high-speed straights bordered by unforgiving walls.',
  },
  'Circuit de Monaco': {
    id: 'monaco',
    name: 'Circuit de Monaco',
    location: 'Monte Carlo',
    country: 'Monaco',
    length: '3.337 km',
    laps: 78,
    lap_record: '1:12.909',
    lap_record_driver: 'Lewis Hamilton (2021)',
    first_gp: 1929,
    type: 'Street',
    elevation: 'Hilly',
    corners: 19,
    drs_zones: 1,
    description: 'The crown jewel of F1. Narrow streets, no margin for error, and the ultimate test of precision and concentration.',
  },
  'Circuit de Barcelona-Catalunya': {
    id: 'barcelona',
    name: 'Circuit de Barcelona-Catalunya',
    location: 'Montmeló',
    country: 'Spain',
    length: '4.657 km',
    laps: 66,
    lap_record: '1:16.330',
    lap_record_driver: 'Max Verstappen (2023)',
    first_gp: 1991,
    type: 'Permanent',
    elevation: 'Undulating',
    corners: 14,
    drs_zones: 2,
    description: 'A classic all-rounder circuit used for pre-season testing. Combines high-speed corners with a technical final sector.',
  },
  'Red Bull Ring': {
    id: 'spielberg',
    name: 'Red Bull Ring',
    location: 'Spielberg',
    country: 'Austria',
    length: '4.318 km',
    laps: 71,
    lap_record: '1:05.619',
    lap_record_driver: 'Carlos Sainz (2020)',
    first_gp: 1970,
    type: 'Permanent',
    elevation: 'Hilly',
    corners: 10,
    drs_zones: 3,
    description: 'A short, sharp blast in the Styrian mountains. Few corners but plenty of action thanks to short lap times and three DRS zones.',
  },
  'Silverstone Circuit': {
    id: 'silverstone',
    name: 'Silverstone Circuit',
    location: 'Silverstone',
    country: 'United Kingdom',
    length: '5.891 km',
    laps: 52,
    lap_record: '1:27.097',
    lap_record_driver: 'Max Verstappen (2020)',
    first_gp: 1950,
    type: 'Permanent',
    elevation: 'Flat',
    corners: 18,
    drs_zones: 2,
    description: 'The home of British motorsport and the first-ever F1 World Championship race. High-speed corners like Copse and Maggotts-Becketts.',
  },
  'Circuit de Spa-Francorchamps': {
    id: 'spa',
    name: 'Circuit de Spa-Francorchamps',
    location: 'Stavelot',
    country: 'Belgium',
    length: '7.004 km',
    laps: 44,
    lap_record: '1:46.286',
    lap_record_driver: 'Valtteri Bottas (2018)',
    first_gp: 1925,
    type: 'Permanent',
    elevation: 'Dramatic',
    corners: 19,
    drs_zones: 2,
    description: 'The longest circuit on the calendar, featuring the legendary Eau Rouge-Raidillon complex and unpredictable Ardennes weather.',
  },
  'Hungaroring': {
    id: 'hungaroring',
    name: 'Hungaroring',
    location: 'Mogyoród',
    country: 'Hungary',
    length: '4.381 km',
    laps: 70,
    lap_record: '1:16.627',
    lap_record_driver: 'Lewis Hamilton (2020)',
    first_gp: 1986,
    type: 'Permanent',
    elevation: 'Undulating',
    corners: 14,
    drs_zones: 2,
    description: 'A tight, twisty circuit often compared to a kart track. Overtaking is difficult, making qualifying crucial.',
  },
  'Circuit Zandvoort': {
    id: 'zandvoort',
    name: 'Circuit Zandvoort',
    location: 'Zandvoort',
    country: 'Netherlands',
    length: '4.259 km',
    laps: 72,
    lap_record: '1:11.097',
    lap_record_driver: 'Lewis Hamilton (2021)',
    first_gp: 1952,
    type: 'Permanent',
    elevation: 'Dramatic',
    corners: 14,
    drs_zones: 2,
    description: 'Returned to F1 in 2021, this coastal circuit features banked Tarzan corner and a passionate orange-clad crowd.',
  },
  'Autodromo Nazionale Monza': {
    id: 'monza',
    name: 'Autodromo Nazionale Monza',
    location: 'Monza',
    country: 'Italy',
    length: '5.793 km',
    laps: 53,
    lap_record: '1:21.046',
    lap_record_driver: 'Rubens Barrichello (2004)',
    first_gp: 1922,
    type: 'Permanent',
    elevation: 'Flat',
    corners: 11,
    drs_zones: 2,
    description: 'The Temple of Speed. Famous for long straights, low downforce setups, and the roaring Tifosi.',
  },
  'Madrid Street Circuit': {
    id: 'madrid',
    name: 'Madrid Street Circuit',
    location: 'Madrid',
    country: 'Spain',
    length: '5.470 km',
    laps: 56,
    lap_record: 'TBD',
    lap_record_driver: 'TBD',
    first_gp: 2026,
    type: 'Street',
    elevation: 'Undulating',
    corners: 20,
    drs_zones: 3,
    description: 'A new addition for 2026, the Madrid street circuit promises fast straights and technical city-centre sections.',
  },
  'Baku City Circuit': {
    id: 'baku',
    name: 'Baku City Circuit',
    location: 'Baku',
    country: 'Azerbaijan',
    length: '6.003 km',
    laps: 51,
    lap_record: '1:43.009',
    lap_record_driver: 'Charles Leclerc (2019)',
    first_gp: 2016,
    type: 'Street',
    elevation: 'Flat',
    corners: 20,
    drs_zones: 2,
    description: 'The longest street circuit on the calendar, mixing medieval old-town tightness with a long blast along the Caspian Sea.',
  },
  'Marina Bay Street Circuit': {
    id: 'singapore',
    name: 'Marina Bay Street Circuit',
    location: 'Singapore',
    country: 'Singapore',
    length: '4.940 km',
    laps: 61,
    lap_record: '1:35.867',
    lap_record_driver: 'Lando Norris (2024)',
    first_gp: 2008,
    type: 'Street',
    elevation: 'Flat',
    corners: 19,
    drs_zones: 4,
    description: 'F1\'s original night race, a punishing street circuit with high humidity, unforgiving walls, and stunning skyline views.',
  },
  'Circuit of the Americas': {
    id: 'cota',
    name: 'Circuit of the Americas',
    location: 'Austin',
    country: 'United States',
    length: '5.513 km',
    laps: 56,
    lap_record: '1:36.169',
    lap_record_driver: 'Charles Leclerc (2019)',
    first_gp: 2012,
    type: 'Permanent',
    elevation: 'Dramatic',
    corners: 20,
    drs_zones: 2,
    description: 'A spectacular American circuit inspired by Silverstone\'s Maggotts-Becketts and the Hockenheimring stadium section.',
  },
  'Autodromo Hermanos Rodriguez': {
    id: 'mexico-city',
    name: 'Autodromo Hermanos Rodriguez',
    location: 'Mexico City',
    country: 'Mexico',
    length: '4.304 km',
    laps: 71,
    lap_record: '1:17.774',
    lap_record_driver: 'Valtteri Bottas (2021)',
    first_gp: 1963,
    type: 'Permanent',
    elevation: 'High',
    corners: 17,
    drs_zones: 3,
    description: 'Set at 2,200m altitude, the thin air boosts straight-line speed and creates unique car-setup challenges.',
  },
  'Interlagos': {
    id: 'interlagos',
    name: 'Autódromo José Carlos Pace (Interlagos)',
    location: 'São Paulo',
    country: 'Brazil',
    length: '4.309 km',
    laps: 71,
    lap_record: '1:10.540',
    lap_record_driver: 'Valtteri Bottas (2018)',
    first_gp: 1973,
    type: 'Permanent',
    elevation: 'Undulating',
    corners: 15,
    drs_zones: 2,
    description: 'A rollercoaster circuit with passionate fans. Famous for Senna\'s legacy and unpredictable, rain-affected races.',
  },
  'Las Vegas Strip Circuit': {
    id: 'las-vegas',
    name: 'Las Vegas Strip Circuit',
    location: 'Las Vegas',
    country: 'United States',
    length: '6.201 km',
    laps: 50,
    lap_record: '1:35.490',
    lap_record_driver: 'Oscar Piastri (2024)',
    first_gp: 2023,
    type: 'Street',
    elevation: 'Flat',
    corners: 17,
    drs_zones: 2,
    description: 'A glamorous night race down the Las Vegas Strip, featuring long straights and a chilly desert environment.',
  },
  'Lusail International Circuit': {
    id: 'lusail',
    name: 'Lusail International Circuit',
    location: 'Lusail',
    country: 'Qatar',
    length: '5.419 km',
    laps: 57,
    lap_record: '1:24.319',
    lap_record_driver: 'Lando Norris (2024)',
    first_gp: 2021,
    type: 'Permanent',
    elevation: 'Flat',
    corners: 16,
    drs_zones: 2,
    description: 'A smooth, fast-flowing desert circuit hosting a night race under floodlights.',
  },
  'Yas Marina Circuit': {
    id: 'yas-marina',
    name: 'Yas Marina Circuit',
    location: 'Abu Dhabi',
    country: 'United Arab Emirates',
    length: '5.281 km',
    laps: 58,
    lap_record: '1:26.103',
    lap_record_driver: 'Max Verstappen (2021)',
    first_gp: 2009,
    type: 'Permanent',
    elevation: 'Flat',
    corners: 16,
    drs_zones: 2,
    description: 'The season finale venue, redesigned in 2021 to improve overtaking. Features a stunning hotel bridge and marina backdrop.',
  },
};
