export const driverBios: Record<string, string> = {
  'lando-norris': 'Reigning World Champion Lando Norris enters his seventh F1 season with McLaren. After a breakthrough 2024 and a dominant 2025 title run, the Briton aims to defend his crown against a hungry grid.',
  'oscar-piastri': 'Australian prodigy Oscar Piastri starts his fourth season with McLaren. A former F3 and F2 champion on debut, Piastri is chasing his first World Championship after leading much of 2025.',
  'max-verstappen': 'Four-time World Champion Max Verstappen remains the talisman of Red Bull Racing. Known for his relentless racecraft, he leads a new-look lineup as the team adapts to 2026 regulations.',
  'isack-hadjar': 'French rookie Isack Hadjar steps up to Red Bull Racing for 2026. A Red Bull junior standout, he arrives with high expectations alongside Max Verstappen.',
  'george-russell': 'Mercedes race winner George Russell enters his eighth F1 season. The Briton is a consistent front-runner and leads Mercedes alongside sensational rookie Kimi Antonelli.',
  'kimi-antonelli': 'Italian sensation Kimi Antonelli makes waves in his rookie F1 season with Mercedes. Already leading the 2026 championship, he is widely tipped as a future superstar.',
  'charles-leclerc': 'Ferrari star Charles Leclerc begins his eighth season with the Scuderia. The Monegasque is a multiple Grand Prix winner and perennial championship contender.',
  'lewis-hamilton': 'Seven-time World Champion Lewis Hamilton embarks on a historic second season with Ferrari. A Barcelona winner in 2026, he continues to rewrite the record books.',
  'alexander-albon': 'Thai-British racer Alex Albon heads Williams with calm authority. A podium finisher, he partners Carlos Sainz to push the Grove team up the order.',
  'carlos-sainz': 'Spanish Grand Prix winner Carlos Sainz joins Williams for 2026. A multiple race winner, he brings experience and aggression to the British outfit.',
  'fernando-alonso': 'Two-time World Champion Fernando Alonso continues his Aston Martin journey. The veteran Spaniard is the oldest driver on the grid but remains as fiercely competitive as ever.',
  'lance-stroll': 'Canadian Lance Stroll starts his tenth F1 season with Aston Martin. Quick in wet conditions, he partners Fernando Alonso for another campaign.',
  'esteban-ocon': 'French race winner Esteban Ocon joins the new-look TGR Haas squad. A combative racer, he leads the American team alongside rookie Oliver Bearman.',
  'oliver-bearman': 'British rookie Oliver Bearman races for Haas in 2026. His impressive stand-in performances in 2024 marked him as one to watch.',
  'nico-hulkenberg': 'German veteran Nico Hülkenberg spearheads Audi’s works F1 entry. A renowned qualifier, he leads a brand-new German factory project.',
  'gabriel-bortoleto': 'Brazilian rookie Gabriel Bortoleto joins Audi for its inaugural F1 season. The 2023 F3 champion arrives as a highly rated Sauber Academy graduate.',
  'pierre-gasly': 'French race winner Pierre Gasly leads Alpine into the 2026 regulations. A Monaco podium finisher this season, he remains one of F1’s most consistent performers.',
  'franco-colapinto': 'Argentine talent Franco Colapinto races his first full F1 season with Alpine. His explosive arrival in 2024 made him a fan favourite.',
  'liam-lawson': 'New Zealander Liam Lawson joins Racing Bulls for 2026. Known for his aggressive style, he is chasing a future promotion to Red Bull Racing.',
  'arvid-lindblad': 'British Red Bull junior Arvid Lindblad steps up to Racing Bulls. The youngest on the grid, he arrives with a glittering junior single-seater record.',
  'valtteri-bottas': 'Finnish veteran Valtteri Bottas joins the new Cadillac F1 entry. A ten-time Grand Prix winner, he brings vast experience to America’s newest team.',
  'sergio-perez': 'Mexican Grand Prix winner Sergio Pérez makes a surprise return with Cadillac for 2026. His racecraft and tyre management make him a valuable asset.',
};

export const driverStats: Record<string, { poles: number; wins: number; podiums: number; fastestLaps: number; gpStarts: number; worldChampionships: number }> = {
  'lando-norris': { poles: 12, wins: 10, podiums: 42, fastestLaps: 11, gpStarts: 122, worldChampionships: 1 },
  'oscar-piastri': { poles: 8, wins: 7, podiums: 28, fastestLaps: 6, gpStarts: 78, worldChampionships: 0 },
  'max-verstappen': { poles: 42, wins: 64, podiums: 112, fastestLaps: 41, gpStarts: 210, worldChampionships: 4 },
  'isack-hadjar': { poles: 0, wins: 0, podiums: 0, fastestLaps: 0, gpStarts: 7, worldChampionships: 0 },
  'george-russell': { poles: 8, wins: 4, podiums: 22, fastestLaps: 8, gpStarts: 138, worldChampionships: 0 },
  'kimi-antonelli': { poles: 3, wins: 4, podiums: 6, fastestLaps: 2, gpStarts: 7, worldChampionships: 0 },
  'charles-leclerc': { poles: 26, wins: 8, podiums: 43, fastestLaps: 11, gpStarts: 154, worldChampionships: 0 },
  'lewis-hamilton': { poles: 104, wins: 106, podiums: 202, fastestLaps: 67, gpStarts: 362, worldChampionships: 7 },
  'alexander-albon': { poles: 0, wins: 0, podiums: 2, fastestLaps: 0, gpStarts: 122, worldChampionships: 0 },
  'carlos-sainz': { poles: 5, wins: 4, podiums: 27, fastestLaps: 4, gpStarts: 216, worldChampionships: 0 },
  'fernando-alonso': { poles: 22, wins: 32, podiums: 106, fastestLaps: 25, gpStarts: 408, worldChampionships: 2 },
  'lance-stroll': { poles: 1, wins: 0, podiums: 3, fastestLaps: 0, gpStarts: 178, worldChampionships: 0 },
  'esteban-ocon': { poles: 0, wins: 1, podiums: 4, fastestLaps: 0, gpStarts: 174, worldChampionships: 0 },
  'oliver-bearman': { poles: 0, wins: 0, podiums: 0, fastestLaps: 0, gpStarts: 7, worldChampionships: 0 },
  'nico-hulkenberg': { poles: 1, wins: 0, podiums: 0, fastestLaps: 2, gpStarts: 228, worldChampionships: 0 },
  'gabriel-bortoleto': { poles: 0, wins: 0, podiums: 0, fastestLaps: 0, gpStarts: 7, worldChampionships: 0 },
  'pierre-gasly': { poles: 0, wins: 1, podiums: 5, fastestLaps: 2, gpStarts: 172, worldChampionships: 0 },
  'franco-colapinto': { poles: 0, wins: 0, podiums: 0, fastestLaps: 0, gpStarts: 9, worldChampionships: 0 },
  'liam-lawson': { poles: 0, wins: 0, podiums: 0, fastestLaps: 0, gpStarts: 11, worldChampionships: 0 },
  'arvid-lindblad': { poles: 0, wins: 0, podiums: 0, fastestLaps: 0, gpStarts: 7, worldChampionships: 0 },
  'valtteri-bottas': { poles: 20, wins: 10, podiums: 67, fastestLaps: 19, gpStarts: 272, worldChampionships: 0 },
  'sergio-perez': { poles: 3, wins: 6, podiums: 39, fastestLaps: 12, gpStarts: 286, worldChampionships: 0 },
};

export const nationalityFlags: Record<string, string> = {
  'British': 'GB', 'Australian': 'AU', 'Dutch': 'NL', 'French': 'FR', 'Italian': 'IT',
  'Monegasque': 'MC', 'Thai': 'TH', 'Spanish': 'ES', 'Canadian': 'CA', 'German': 'DE',
  'Brazilian': 'BR', 'Argentine': 'AR', 'New Zealander': 'NZ', 'Finnish': 'FI', 'Mexican': 'MX'
};
